[env]
  NIXPACKS_PHP_VERSION = "8.4"
  LARAVEL_BYPASS_ENV_CHECK = "1"

[providers]
  php = true
  python = true

[phases.install]
  cmds = [
    "composer install --no-dev --optimize-autoloader",
    "pip install pandas joblib scikit-learn"
  ]

[phases.build]
  # Override Laravel's default build phase to stop it from running 'php artisan migrate'
  cmds = [
    "php artisan optimize:clear",
    "php artisan config:cache",
    "php artisan route:cache"
  ]

[phases.start]
  cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"